## Overrides ##

# Place your custom options here
# Options placed here will not be touched after an update
# Copy options from the base config or go to the hyprland wiki for more options
# See examples below

# Keyboard layout
# Go to https://wiki.hyprland.org/Configuring/Variables/#input for more information
input {
    kb_layout = us, latam
    kb_variant =
    kb_options = grp:win_space_toggle
}

# Go to /etc/sddm.conf.d/hyprland.conf to edit sddm's monitor settings
# Go to https://wiki.hyprland.org/Configuring/Monitors/ for more information
#
# monitor = name, resolution, position, scale

# PC de mesa
#
#monitor = HDMI-A-1, 1920x1080@60, 0x0, 1
#monitor = HDMI-A-2, 1600x1200@60, 1920x0, 1



# Portatil
#monitor = eDP-1, 1920x1080@60, 0x0, 1
#monitor = HDMI-A-1, 1920x1080@60, 0x0, 1, mirror, eDP-1
#monitor  = DP-1, 1920x1080@60, 1920x0, 1


# EXAMPLE: Uncomment below to change layout from master to dwindle
#
# general {
#     layout = dwindle
# }
general {
    gaps_in = 0
    gaps_out = 0
    border_size = 2
    # Set active window borders to pywal color
    col.active_border = $color3
    col.inactive_border = 0xff363737
    layout = master

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}

# EXAMPLE: Uncomment below to rebind close window to SUPER + C
# NOTE: Keybind changes will be reflected in the actions menu after a refresh
#
# unbind = SUPER, Q
# unbind = SUPER, C
# bind = SUPER, C, killactive # Close window

# EXAMPLE: Uncomment below to make your own Keybinds configuration
#
# source = Keybinds.conf
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = pcloud


bind = SUPER, C, exec, gromit-mpx -a#gromit
bind = SUPER, X, exec, obs #obs
bind = SUPER, Z, exec, xournalpp #xournalpp


device {
    name = ugtablet-m708-pen
    output = HDMI-A-1
}

windowrule {
  name = gromit-crisp
  match:class = ^(gromit-mpx|Gromit-mpx)$

  no_blur = on
  no_dim = on
  opacity = 1.0 override 1.0 override 1.0 override

  # Opcionales (prueba si aún lo notas raro):
  # opaque = on
  # force_rgbx = on

  # Si quieres comportamiento tipo overlay:
  float = on
  pin = on
}

# portatil

